export const Data = [
  {
    period: 'Semestre 1',
    subjects: [
      {
        sigla: 'IAL102',
        titulo: 'Algoritmos e Lógica de Programação',
        status: 'aprovado',
        nf: 7,
        freq: 95,
        dia_aula: 'segunda-feira',
        hora: '12:00',
      },
      {
        sigla: 'ING007',
        titulo: 'Inglês I',
        status: 'aprovado',
        nf: 7,
        freq: 100,
        dia_aula: 'terça-feira',
        hora: '08:00',
      },
      {
        sigla: 'ISW002',
        titulo: 'Bases da Internet',
        status: 'aprovado',
        nf: 9.6,
        freq: 85,
        dia_aula: 'quarta-feira',
        hora: '11:00',
      },
      {
        sigla: 'ISW003',
        titulo: 'Criação de Conteúdo na Web',
        status: 'aprovado',
        nf: 6.5,
        freq: 95,
        dia_aula: 'quinta-feira',
        hora: '09:30',
      },
      {
        sigla: 'ISW004',
        titulo: 'Design Digital',
        status: 'aprovado',
        nf: 7.5,
        freq: 100,
        dia_aula: 'segunda-feira',
        hora: '08:00',
      },
      {
        sigla: 'ISW005',
        titulo: 'Padrões de Projeto de Sítios Internet I',
        status: 'aprovado',
        nf: 8.2,
        freq: 90,
        dia_aula: 'sexta-feira',
        hora: '08:00',
      },
      {
        sigla: 'MAT003',
        titulo: 'Fundamentos de Matemática Elementar',
        status: 'aprovado',
        nf: 7,
        freq: 100,
        dia_aula: 'sexta-feira',
        hora: '09:30',
      },
    ],
  },
  {
    period: 'Semestre 2',
    subjects: [
      {
        sigla: 'DDI004',
        titulo: 'Legislação Aplicada à Internet',
        status: 'aprovado',
        nf: 6.2,
        freq: 90,
        dia_aula: 'sexta-feira',
        hora: '09:30',
      },
      {
        sigla: 'IED001',
        titulo: 'Estruturas de Dados',
        status: 'aprovado',
        nf: 6,
        freq: 100,
        dia_aula: 'segunda-feira',
        hora: '09:30',
      },
      {
        sigla: 'ING008',
        titulo: 'Inglês II',
        status: 'aprovado',
        nf: 6,
        freq: 100,
        dia_aula: 'terça-feira',
        hora: '09:30',
      },
      {
        sigla: 'IRC009',
        titulo: 'Redes e Internet',
        status: 'aprovado',
        nf: 6,
        freq: 100,
        dia_aula: 'quinta-feira',
        hora: '09:30',
      },
      {
        sigla: 'ISW006',
        titulo: 'Padrões de Projeto de Sítios Internet II',
        status: 'aprovado',
        nf: 6,
        freq: 100,
        dia_aula: 'quarta-feira',
        hora: '08:00',
      },
      {
        sigla: 'ISW007',
        titulo: 'Prática de Design',
        status: 'aprovado',
        nf: 6,
        freq: 100,
        dia_aula: 'segunda-feira',
        hora: '08:00',
      },
      {
        sigla: 'MMD003',
        titulo: 'Matemática Discreta',
        status: 'aprovado',
        nf: 7.2,
        freq: 100,
        dia_aula: 'quarta-feira',
        hora: '09:30',
      },
    ],
  },
  {
    period: 'Semestre 3',
    subjects: [
      {
        sigla: 'IBD005',
        titulo: 'Banco de Dados e Internet I',
        status: 'aprovado',
        nf: 6.2,
        freq: 100,
        dia_aula: 'quarta-feira',
        hora: '09:30',
      },
      {
        sigla: 'IES003',
        titulo: 'Engenharia de Software para WEB',
        status: 'aprovado',
        nf: 8.5,
        freq: 100,
        dia_aula: 'terça-feira',
        hora: '09:30',
      },
      {
        sigla: 'ING009',
        titulo: 'Inglês III',
        status: 'aprovado',
        nf: 7,
        freq: 100,
        dia_aula: 'quinta-feira',
        hora: '09:30',
      },
      {
        sigla: 'ISO004',
        titulo: 'Servidores e seus Sistemas Operacionais',
        status: 'aprovado',
        nf: 9.5,
        freq: 95,
        dia_aula: 'segunda-feira',
        hora: '08:00',
      },
      {
        sigla: 'ISW008',
        titulo: 'Programação de Sítios Internet',
        status: 'aprovado',
        nf: 6.6,
        freq: 95,
        dia_aula: 'quarta-feira',
        hora: '09:30',
      },
      {
        sigla: 'ISW009',
        titulo: 'Acessibilidade',
        status: 'aprovado',
        nf: 6,
        freq: 100,
        dia_aula: 'terça-feira',
        hora: '08:00',
      },
      {
        sigla: 'MET002',
        titulo: 'Estatística',
        status: 'aprovado',
        nf: 6.5,
        freq: 95,
        dia_aula: 'sexta-feira',
        hora: '09:30',
      },
    ],
  },
  {
    period: 'Semestre 4',
    subjects: [
      {
        sigla: 'AGO011',
        titulo: 'Prática de Gestão de Projetos',
        status: 'cursando',
        nf: 3,
        freq: 100,
        dia_aula: 'sexta-feira',
        hora: '08:00',
      },
      {
        sigla: 'IBD006',
        titulo: 'Banco de Dados e Internet II',
        status: 'cursando',
        nf: 7.5,
        freq: 100,
        dia_aula: 'quarta-feira',
        hora: '09:30',
      },
      {
        sigla: 'IDS001',
        titulo: 'Desenvolvimento para Servidores I',
        status: 'aprovado',
        nf: 6.6,
        freq: 90,
        dia_aula: 'segunda-feira',
        hora: '09:30',
      },
      {
        sigla: 'ING010',
        titulo: 'Inglês IV',
        status: 'aprovado',
        nf: 6.2,
        freq: 100,
        dia_aula: 'terça-feira',
        hora: '09:30',
      },
      {
        sigla: 'ISG018',
        titulo: 'Segurança em Sistemas para Internet',
        status: 'aprovado',
        nf: 8.8,
        freq: 95,
        dia_aula: 'sexta-feira',
        hora: '09:30',
      },
      {
        sigla: 'ISW010',
        titulo: 'Projeto de Navegação e Interação',
        status: 'aprovado',
        nf: 7,
        freq: 100,
        dia_aula: 'quinta-feira',
        hora: '09:30',
      },
      {
        sigla: 'ITE003',
        titulo: 'Tópicos Especiais em Sistemas para Internet I',
        status: 'aprovado',
        nf: 6,
        freq: 100,
        dia_aula: 'sexta-feira',
        hora: '09:30',
      },
    ],
  },
  {
    period: 'Semestre 5',
    subjects: [
      {
        sigla: 'AGM004',
        titulo: 'Negócios e Marketing e Eletrônicos',
        status: 'cursando',
        nf: 6.5,
        freq: 0,
        dia_aula: 'quarta-feira',
        hora: '19:00',
      },
      {
        sigla: 'IDS002',
        titulo: 'Desenvolvimento para Servidores II',
        status: 'cursando',
        nf: 0,
        freq: 0,
        dia_aula: 'quinta-feira',
        hora: '19:00',
      },
      {
        sigla: 'ING011',
        titulo: 'Inglês V',
        status: 'cursando',
        nf: 7.7,
        freq: 0,
        dia_aula: 'terça-feira',
        hora: '19:00',
      },
      {
        sigla: 'ISW011',
        titulo: 'Projeto de Prototipagem e Testes de Usabilidade',
        status: 'cursando',
        nf: 3.5,
        freq: 0,
        dia_aula: 'sábado',
        hora: '08:00',
      },
      {
        sigla: 'ISW012',
        titulo: 'Desenvolvimento para Dispositivos Móveis I',
        status: 'cursando',
        nf: 5,
        freq: 0,
        dia_aula: 'segunda-feira',
        hora: '19:00',
      },
      {
        sigla: 'ITE004',
        titulo: 'Tópicos Especiais em Sistemas para Internet II',
        status: 'cursando',
        nf: 0,
        freq: 0,
        dia_aula: 'sexta-feira',
        hora: '19:00',
      },
      {
        sigla: 'TTG401',
        titulo: 'Projeto de Trabalho de Graduação em Sistemas para Internet I',
        status: 'cursando',
        nf: 0,
        freq: 100,
        dia_aula: 'sábado',
        hora: '11:00',
      },
    ],
  },
];
